name: on one branch

on:
  push:
    branches:
      feature-1
      
jobs:
  printing_shell_script:
    name: Running shell script
    runs-on: ubuntu-latest
    
    steps: 
      
      - name: run shell
        run: |
         #!/bin/bash
        
          echo Executing for loop

          for i in {1..10}
          do
          echo Number is $i
          done
          
      - name: run while loop
        run: |
         #!/bin/bash
         
          echo Eecuting while loop
          count=1
          while [ $count -le 10 ]
          do
          echo "Number is $count"
          let count++
          done
          
